version: "3.8"

services:
    php:
        container_name: php
        working_dir: /app
        build:
            context: ./build/php
            dockerfile: Dockerfile
        volumes:
            - .:/app
    nginx:
        container_name: nginx
        image: arm64v8/nginx:alpine
        volumes:
            - .:/app
            - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./build/nginx/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
    postgres:
        container_name: postgres
        image: arm64v8/postgres
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - ./build/data/postgres:/var/lib/postgresql/data
